### ISSUE TITLE
How do you convert the *.torchm files into the format usable by the mtcnn module (pnet.npy, rnet.npy, onet.npy)?

### ISSUE THREAD

**Issue by gerald-ftk** [BrightXiaoHan/FaceDetector#11]
I've followed the training code, and successfully created the pnet.torchm, rnet.torchm, onet.torchm files, but how to I make them useable by mtcnn? Right now when I try to load them with mtcnn it throws a `raise KeyError("%s is not a file in the archive" % key)
TypeError: not enough arguments for format string`

**Comment by BrightXiaoHan** [comment]
You can use **get_net** method in mtcnn/deploy/__init__.py

**Comment by AwatefEdhibb** [comment]
hello thanks for this work, 
how can i do convert *.torchm to *.npy model
any help please
